import Foundation

/// Default payees supplied with the app. Shared domains still represent distinct payees.
enum BundledPayees {
  struct Entry {
    var name: String
    var domain: String
  }

  static let entries: [Entry] = [
    .init(name: "Walmart", domain: "walmart.com"),
    .init(name: "Amazon", domain: "amazon.com"),
    .init(name: "Costco Wholesale", domain: "costco.com"),
    .init(name: "The Kroger Co.", domain: "kroger.com"),
    .init(name: "The Home Depot", domain: "homedepot.com"),
    .init(name: "Target", domain: "target.com"),
    .init(name: "Walgreens", domain: "walgreens.com"),
    .init(name: "CVS Pharmacy", domain: "cvs.com"),
    .init(name: "Lowe's", domain: "lowes.com"),
    .init(name: "Albertsons", domain: "albertsons.com"),
    .init(name: "Apple", domain: "apple.com"),
    .init(name: "Best Buy", domain: "bestbuy.com"),
    .init(name: "Publix", domain: "publix.com"),
    .init(name: "The TJX Companies (TJ Maxx, Marshalls)", domain: "tjx.com"),
    .init(name: "H-E-B", domain: "heb.com"),
    .init(name: "Zara", domain: "zara.com"),
    .init(name: "H&M", domain: "hm.com"),
    .init(name: "Uniqlo", domain: "uniqlo.com"),
    .init(name: "ASOS", domain: "asos.com"),
    .init(name: "Urban Outfitters", domain: "urbanoutfitters.com"),
    .init(name: "Anthropologie", domain: "anthropologie.com"),
    .init(name: "Free People", domain: "freepeople.com"),
    .init(name: "Shein", domain: "shein.com"),
    .init(name: "Old Navy", domain: "oldnavy.com"),
    .init(name: "Banana Republic", domain: "bananarepublic.com"),
    .init(name: "J.Crew", domain: "jcrew.com"),
    .init(name: "Madewell", domain: "madewell.com"),
    .init(name: "American Eagle", domain: "ae.com"),
    .init(name: "Aerie", domain: "aerie.com"),
    .init(name: "Abercrombie & Fitch", domain: "abercrombie.com"),
    .init(name: "Hollister", domain: "hollisterco.com"),
    .init(name: "Levi's", domain: "levi.com"),
    .init(name: "Express", domain: "express.com"),
    .init(name: "Mango", domain: "mango.com"),
    .init(name: "Victoria's Secret", domain: "victoriassecret.com"),
    .init(name: "Calvin Klein", domain: "calvinklein.com"),
    .init(name: "Tommy Hilfiger", domain: "tommy.com"),
    .init(name: "Ralph Lauren", domain: "ralphlauren.com"),
    .init(name: "Nordstrom", domain: "nordstrom.com"),
    .init(name: "Bloomingdale's", domain: "bloomingdales.com"),
    .init(name: "Neiman Marcus", domain: "neimanmarcus.com"),
    .init(name: "Saks Fifth Avenue", domain: "saksfifthavenue.com"),
    .init(name: "Patagonia", domain: "patagonia.com"),
    .init(name: "The North Face", domain: "thenorthface.com"),
    .init(name: "Lululemon", domain: "lululemon.com"),
    .init(name: "Nike", domain: "nike.com"),
    .init(name: "Adidas", domain: "adidas.com"),
    .init(name: "Sephora", domain: "sephora.com"),
    .init(name: "Ulta Beauty", domain: "ulta.com"),
    .init(name: "MAC Cosmetics", domain: "maccosmetics.com"),
    .init(name: "Glossier", domain: "glossier.com"),
    .init(name: "Fenty Beauty", domain: "fentybeauty.com"),
    .init(name: "Charlotte Tilbury", domain: "charlottetilbury.com"),
    .init(name: "Rare Beauty", domain: "rarebeauty.com"),
    .init(name: "e.l.f. Cosmetics", domain: "elfcosmetics.com"),
    .init(name: "NYX Professional Makeup", domain: "nyxcosmetics.com"),
    .init(name: "ColourPop", domain: "colourpop.com"),
    .init(name: "L'Oréal", domain: "loreal.com"),
    .init(name: "Maybelline", domain: "maybelline.com"),
    .init(name: "Estée Lauder", domain: "esteelauder.com"),
    .init(name: "Clinique", domain: "clinique.com"),
    .init(name: "Lancôme", domain: "lancome.com"),
    .init(name: "The Ordinary", domain: "theordinary.com"),
    .init(name: "Paula's Choice", domain: "paulaschoice.com"),
    .init(name: "Bath & Body Works", domain: "bathandbodyworks.com"),
    .init(name: "Dollar General", domain: "dollargeneral.com"),
    .init(name: "McDonald's", domain: "mcdonalds.com"),
    .init(name: "Starbucks", domain: "starbucks.com"),
    .init(name: "Meijer", domain: "meijer.com"),
    .init(name: "Macy's", domain: "macys.com"),
    .init(name: "Dollar Tree", domain: "dollartree.com"),
    .init(name: "Ace Hardware", domain: "acehardware.com"),
    .init(name: "ALDI", domain: "aldi.us"),
    .init(name: "Kohl's", domain: "kohls.com"),
    .init(name: "Ross Stores", domain: "rossstores.com"),
    .init(name: "AutoZone", domain: "autozone.com"),
    .init(name: "O'Reilly Auto Parts", domain: "oreillyauto.com"),
    .init(name: "Tractor Supply Co.", domain: "tractorsupply.com"),
    .init(name: "Dick's Sporting Goods", domain: "dickssportinggoods.com"),
    .init(name: "Wayfair", domain: "wayfair.com"),
    .init(name: "Chewy", domain: "chewy.com"),
    .init(name: "Wawa", domain: "wawa.com"),
    .init(name: "7-Eleven", domain: "7-eleven.com"),
    .init(name: "Chick-fil-A", domain: "chick-fil-a.com"),
    .init(name: "Wendy's", domain: "wendys.com"),
    .init(name: "Taco Bell", domain: "tacobell.com"),
    .init(name: "Dunkin'", domain: "dunkindonuts.com"),
    .init(name: "Whole Foods Market", domain: "wholefoodsmarket.com"),
    .init(name: "Trader Joe's", domain: "traderjoes.com"),
    .init(name: "GameStop", domain: "gamestop.com"),
    .init(name: "PetSmart", domain: "petsmart.com"),
    .init(name: "Petco", domain: "petco.com"),
    .init(name: "AT&T", domain: "att.com"),
    .init(name: "Verizon", domain: "verizon.com"),
    .init(name: "T-Mobile", domain: "t-mobile.com"),
    .init(name: "Gap", domain: "gap.com"),
    .init(name: "Uber", domain: "uber.com"),
    .init(name: "Lyft", domain: "lyft.com"),
    .init(name: "DoorDash", domain: "doordash.com"),
    .init(name: "Uber Eats", domain: "ubereats.com"),
    .init(name: "Grubhub", domain: "grubhub.com"),
    .init(name: "Postmates", domain: "postmates.com"),
    .init(name: "Instacart", domain: "instacart.com"),
    .init(name: "Domino's", domain: "dominos.com"),
    .init(name: "Pizza Hut", domain: "pizzahut.com"),
    .init(name: "Papa Johns", domain: "papajohns.com"),
    .init(name: "Little Caesars", domain: "littlecaesars.com"),
    .init(name: "Marco's Pizza", domain: "marcos.com"),
    .init(name: "Portillo's", domain: "portillos.com"),
    .init(name: "Lou Malnati's", domain: "loumalnatis.com"),
    .init(name: "Giordano's", domain: "giordanos.com"),
    .init(name: "Gino's East", domain: "ginoseast.com"),
    .init(name: "Pequod's Pizza", domain: "pequodspizza.com"),
    .init(name: "Garrett Popcorn Shops", domain: "garrettpopcorn.com"),
    .init(name: "Intelligentsia Coffee", domain: "intelligentsia.com"),
    .init(name: "Al's Beef", domain: "alsbeef.com"),
    .init(name: "Harold's Chicken Shack", domain: "haroldschickenshack.com"),
    .init(name: "Do-Rite Donuts", domain: "doritedonuts.com"),
    .init(name: "The Original Rainbow Cone", domain: "rainbowcone.com"),
    .init(name: "OpenAI", domain: "openai.com"),
    .init(name: "Anthropic", domain: "anthropic.com"),
    .init(name: "Google", domain: "google.com"),
    .init(name: "Perplexity", domain: "perplexity.ai"),
    .init(name: "Microsoft", domain: "microsoft.com"),
    .init(name: "Notion", domain: "notion.so"),
    .init(name: "Evernote", domain: "evernote.com"),
    .init(name: "Todoist", domain: "todoist.com"),
    .init(name: "Trello", domain: "trello.com"),
    .init(name: "Asana", domain: "asana.com"),
    .init(name: "Monday.com", domain: "monday.com"),
    .init(name: "ClickUp", domain: "clickup.com"),
    .init(name: "Venmo", domain: "venmo.com"),
    .init(name: "PayPal", domain: "paypal.com"),
    .init(name: "Zelle", domain: "zellepay.com"),
    .init(name: "Cash App", domain: "cash.app"),
    .init(name: "Chase", domain: "chase.com"),
    .init(name: "Bank of America", domain: "bankofamerica.com"),
    .init(name: "Wells Fargo", domain: "wellsfargo.com"),
    .init(name: "Citi", domain: "citi.com"),
    .init(name: "Capital One", domain: "capitalone.com"),
    .init(name: "American Express", domain: "americanexpress.com"),
    .init(name: "Discover", domain: "discover.com"),
    .init(name: "USAA", domain: "usaa.com"),
    .init(name: "PNC Bank", domain: "pnc.com"),
    .init(name: "U.S. Bank", domain: "usbank.com"),
    .init(name: "Netflix", domain: "netflix.com"),
    .init(name: "Hulu", domain: "hulu.com"),
    .init(name: "Disney+", domain: "disneyplus.com"),
    .init(name: "Max", domain: "max.com"),
    .init(name: "Amazon Prime Video", domain: "amazon.com"),
    .init(name: "Apple TV+", domain: "apple.com"),
    .init(name: "Peacock", domain: "peacocktv.com"),
    .init(name: "Paramount+", domain: "paramountplus.com"),
    .init(name: "Spotify", domain: "spotify.com"),
    .init(name: "Apple Music", domain: "apple.com"),
    .init(name: "YouTube TV", domain: "tv.youtube.com"),
    .init(name: "Dutch Bros Coffee", domain: "dutchbros.com"),
    .init(name: "Tim Hortons", domain: "timhortons.com"),
    .init(name: "Scooter's Coffee", domain: "scooterscoffee.com"),
    .init(name: "Caribou Coffee", domain: "cariboucoffee.com"),
    .init(name: "Biggby Coffee", domain: "biggby.com"),
    .init(name: "Peet's Coffee", domain: "peets.com"),
    .init(name: "The Coffee Bean & Tea Leaf", domain: "coffeebean.com"),
    .init(name: "7 Brew Drive Thru Coffee", domain: "7brew.com"),
    .init(name: "Panera Bread", domain: "panerabread.com"),
    .init(name: "Blue Bottle Coffee", domain: "bluebottlecoffee.com"),
    .init(name: "La Colombe", domain: "lacolombe.com"),
    .init(name: "Philz Coffee", domain: "philzcoffee.com"),
    .init(name: "PJ's Coffee", domain: "pjscoffee.com"),
    .init(name: "Stumptown Coffee Roasters", domain: "stumptowncoffee.com"),
    .init(name: "Blank Street Coffee", domain: "blankstreet.com"),
    .init(name: "Gloria Jean's Coffees", domain: "gloriajeans.com"),
    .init(name: "Dunn Brothers Coffee", domain: "dunnbrothers.com"),
    .init(name: "Black Rock Coffee Bar", domain: "br.coffee"),
    .init(name: "Gregorys Coffee", domain: "gregoryscoffee.com"),
    .init(name: "Pret A Manger", domain: "pret.com")
  ]
}
